version: "3"
services:
  db:
    image: postgres:16
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
       - POSTGRES_USER=postgres 
       - POSTGRES_PASSWORD=postgres
  redis:
    image: redis:6.0

  web:
    #build: .
    image: aborodiy/ruby-test-app:latest   
    command: bash config/run.sh
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis