version: "3"
services:
  db:
    image: keinos/sqlite3:latest
  web:
    build: .
    #image: rubyrail:latest   
    command: puma -p 3000
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  redis:
    image: redis:6.0

