name: Docker build and push image
on: 
    push:
        branches: 
        - main 
        - qa 
        - staging
jobs:
    build_images:  
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: build image
              run: docker build . -t aborodiy/ruby-test-app:${{github.sha}}-$(date +%s)
            - name: push image to DockerHub
              run: |
                docker login -u aborodiy -p ${{secrets.DOCKER_HUB_TOKEN}}
                docker push aborodiy/ruby-test-app:latest



