name: Docker build and push image
on: 
    push:
        branches: 
        - main 
        - qa 
        - staging
jobs:
    build-push:
        env:
            IMAGE: aborodiy/ruby-test-app
        runs-on: ubuntu-latest
        steps:

            - name: Generate build ID
              id: prep
              run: |
                    branch=${GITHUB_REF##*/}
                    sha=${GITHUB_SHA::8}
                    ts=$(date +%s)
                    echo "::set-output name=BUILD_ID::${branch}-${sha}-${ts}" 
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            
            - name: Docker Login
              uses: docker/login-action@v3.3.0
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKER_HUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v6
              with: 
                push: true
                tags: |
                    ${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }}
                cache-from: type=gha
                cache-to: type=gha,mode=max            


