name: Docker build and push image
on:  
    pull_request:
        types: [opened, closed]
        branches:
        - main  
        - 'feature/**'
jobs:
    job_for_pr:
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        runs-on: ubuntu-latest
        steps:
          - name: adasd
            run: "This is a pull request on a feature branch"
    job_for_acc_pr:
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true&& github.event.pull_request.base.ref == 'main'
        env:
            IMAGE: aborodiy/ruby-test-app
        runs-on: ubuntu-latest
        steps:
            - name: Generate build ID
              id: prep
              run: |
                    branch=${GITHUB_REF##*/}
                    sha=${GITHUB_SHA::8}
                    ts=$(date +%F.%H%M%S) 
                    echo "BUILD_ID=${branch}-${sha}-${ts}" >>$GITHUB_OUTPUT
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            
            - name: Docker Login
              uses: docker/login-action@v3.3.0
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKER_HUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v6
              with: 
                push: true
                tags: |
                    ${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }}
                cache-from: type=registry,ref=aborodiy/ruby-app:buildcache
                cache-to: type=registry,ref=aborodiy/ruby-app:buildcache,mode=max