name: Docker build and push image
on: 
    
    push:
        branches: 
        - main 
        - qa 
        - staging
jobs:
    build_images:  
        runs-on: ubuntu-latest
        steps:

            -
                name: Current date time
                id: t
                uses: kaven-universe/github-action-current-date-time@v1.4.0
                with:
                  format: "YYYY_MM_DD HH_mm_ss_SSS"
            -
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3
            
            - 
             name: Docker Login
             uses: docker/login-action@v3.3.0
             with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKER_HUB_TOKEN }}
            -
              name: Build and push
              uses: docker/build-push-action@v6
              with: 
                push: true
                tags: aborodiy/ruby-test-app:${{github.ref_name}}-${{github.sha}}-${{ steps.t.outputs.time }}
            


